"""Turns clustered log data into a Markdown report.

Offline mode lists clusters ranked by frequency with sample lines — no
network access required. If ANTHROPIC_API_KEY is set, the top clusters
are also sent to Claude for a short root-cause / next-steps summary,
which gets prepended to the report.
"""

from __future__ import annotations
import os
from logsentry.clustering import Cluster

SYSTEM_PROMPT = (
    "You are an SRE reviewing clustered application log errors. For each "
    "cluster given (its log level, message template, occurrence count, "
    "and sample lines), briefly note a likely root cause and one concrete "
    "next step to investigate or mitigate it. Be specific and grounded in "
    "what the template actually says — do not invent causes it doesn't "
    "support. Keep the whole response under 300 words, formatted as a "
    "Markdown bullet list, one bullet per cluster, ordered the same as "
    "given. No preamble."
)


def render_offline_report(clusters: list[Cluster], top_n: int = 20) -> str:
    lines = ["# Log Cluster Report", "", "_Generated by logsentry (offline mode)._", ""]
    lines.append(f"Found {len(clusters)} distinct message pattern(s).")
    lines.append("")

    for i, cluster in enumerate(clusters[:top_n], start=1):
        lines.append(f"### {i}. [{cluster.level}] × {cluster.count} — `{cluster.template}`")
        lines.append("")
        for sample in cluster.samples:
            lines.append(f"    {sample}")
        lines.append("")

    return "\n".join(lines)


def _build_cluster_prompt(clusters: list[Cluster], top_n: int) -> str:
    parts = []
    for i, cluster in enumerate(clusters[:top_n], start=1):
        samples = "\n    ".join(cluster.samples)
        parts.append(
            f"{i}. level={cluster.level} count={cluster.count} template={cluster.template}\n    {samples}"
        )
    return "\n\n".join(parts)


def generate_ai_summary(clusters: list[Cluster], top_n: int = 10) -> str | None:
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key or not clusters:
        return None

    try:
        import anthropic
    except ImportError:
        return None

    try:
        client = anthropic.Anthropic(api_key=api_key)
        response = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=600,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": _build_cluster_prompt(clusters, top_n)}],
        )
        text_blocks = [b.text for b in response.content if getattr(b, "type", None) == "text"]
        return "\n".join(text_blocks).strip() or None
    except Exception:
        return None


def generate_report(clusters: list[Cluster], use_ai: bool = True, top_n: int = 20) -> str:
    reference = render_offline_report(clusters, top_n=top_n)

    summary = generate_ai_summary(clusters, top_n=min(top_n, 10)) if use_ai else None
    if summary:
        return f"# Root Cause Summary\n\n{summary}\n\n---\n\n{reference}"

    return reference
